In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.model_selection import train_test_split

In [1]:
x, y = zip(['a', 1], ['b', 2], ['c', 3])
print(x)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [2]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
x, y = zip(*sequences)
print(x)
print(y)


('a', 'b', 'c')
(1, 2, 3)


In [4]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
          ['내일 뵐 수 있을지 확인 부탁드...', ]]
columns = ['메일 본문', '스팸 매일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 매일 유무
0      당신에게 드리는 마지막 혜택!       1.0
1  내일 뵐 수 있을지 확인 부탁드...       NaN

In [6]:
X = df('X 데:', X,.to_list())
Y = df('Y 데:', Y,.to_list())

SyntaxError: ignored

In [7]:
X = df['메일 본문']
y = df['스팸 메일 유무']

print('X 데이터 :',X.to_list())
print('y 데이터 :',y.to_list())


KeyError: ignored

In [ ]:
import numpy as np

np.array = 

In [8]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df


메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [9]:
X = df['메일 본문']
y = df['스팸 메일 유무']

print('X 데이터 :',X.to_list())
print('y 데이터 :',y.to_list())

X 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


In [10]:
import numpy as np

np.array = np.arange(0, 16).reshape((4,4))
print(np.array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

TypeError: ignored

In [12]:
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)


전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

TypeError: ignored

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)


NameError: ignored

In [18]:
import numpy as np
from sklearn.model_selection import train_test_split

X, y = np.arange(10).reshape((5, 2)), range(5)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
X_train


TypeError: ignored

In [19]:
import numpy as np
from sklearn.model_selection import train_test_split

X, y = np.arange(10).reshape((5, 2)), range(5)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)
X_train


TypeError: ignored

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)
print(X_train)
print(X_train)

NameError: ignored

In [ ]:
import numpy as np


In [21]:
print(X_test)
print(list(y_test))

NameError: ignored

In [22]:
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-ykbyf3b6
  Running command git clone -q https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-ykbyf3b6
     |████████████████████████████████| 671.4 MB 1.8 kB/s 
     |████████████████████████████████| 463 kB 58.1 MB/s 
     |████████████████████████████████| 1.3 MB 59.5 MB/s 
  Created wheel for pykospacing: filename=pykospacing-0.5-py3-none-any.whl size=2268577 sha256=8a0c00c2538dd38166d30fa2064b765ea2a1c8fd22672015638ca20dbad29f00
  Stored in directory: /tmp/pip-ephem-wheel-cache-mbu3gkx0/wheels/9b/93/81/a2a7dc8c66ede5bf30634d20635f32b95eac7ca2ea8844058b
Successfully built pykospacing
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempt